"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { SlidersHorizontal, X } from "lucide-react";
import { ProductCard } from "@/components/ProductCard";
import type { Audience, Product, ProductType } from "@/types/product";

const audienceLabels: Record<Audience, string> = { women: "Nữ", men: "Nam", kids: "Trẻ em", unisex: "Unisex" };
const typeLabels: Record<ProductType, string> = { shoes: "Giày dép", belts: "Dây lưng", wallets: "Ví & Balo", food: "Thực phẩm" };

type CatalogPageProps = { products: Product[]; audience?: Audience; productType?: ProductType; title: string; query?: string };

export function CatalogPage({ products, audience, productType, title, query }: CatalogPageProps) {
  const [filterOpen, setFilterOpen] = useState(false);
  const [category, setCategory] = useState("");
  const [size, setSize] = useState("");
  const [sort, setSort] = useState("newest");
  const categories = Array.from(new Set(products.map((product) => product.category)));
  const sizes = Array.from(new Set(products.flatMap((product) => product.variants?.map((variant) => variant.size) ?? []))).sort((a, b) => Number(a) - Number(b));
  const visibleProducts = useMemo(() => products.filter((product) => (!category || product.category === category) && (!size || product.variants?.some((variant) => variant.size === size))).sort((a, b) => sort === "price-asc" ? a.price - b.price : sort === "price-desc" ? b.price - a.price : 0), [category, products, size, sort]);
  const filters = <div className="grid gap-6"><div><h2 className="text-xs font-black uppercase tracking-[.14em]">Danh mục</h2><div className="mt-3 grid gap-2">{["", ...categories].map((item) => <button className={`text-left text-sm ${category === item ? "font-black text-shopo-orange" : "text-neutral-600"}`} type="button" onClick={() => setCategory(item)} key={item || "all"}>{item ? item.replaceAll("-", " ") : "Tất cả"}</button>)}</div></div><div><h2 className="text-xs font-black uppercase tracking-[.14em]">Kích cỡ</h2><div className="mt-3 flex flex-wrap gap-2">{sizes.map((item) => <button className={`min-w-10 border px-3 py-2 text-xs font-bold ${size === item ? "border-ink bg-ink text-white" : "border-neutral-200"}`} onClick={() => setSize(size === item ? "" : item)} type="button" key={item}>{item}</button>)}</div></div></div>;
  return <main className="mx-auto max-w-[1440px] px-4 py-10 sm:px-6 lg:px-8"><nav className="text-xs font-bold uppercase tracking-[.12em] text-neutral-500"><Link href="/">Trang chủ</Link> / {audience ? audienceLabels[audience] : "Tìm kiếm"} {productType ? ` / ${typeLabels[productType]}` : ""}</nav><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-shopo-orange">SHOPO Collection</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em] sm:text-5xl">{title}</h1>{query ? <p className="mt-3 text-sm text-neutral-600">Kết quả cho “{query}”</p> : null}</div><p className="text-sm text-neutral-500">{visibleProducts.length} sản phẩm</p></div><div className="mt-8 grid gap-8 lg:grid-cols-[220px_1fr]"><aside className="sticky top-32 hidden h-fit border-t border-neutral-200 pt-5 lg:block">{filters}</aside><section><div className="mb-5 flex items-center justify-between border-y border-neutral-200 py-3"><button className="inline-flex items-center gap-2 text-xs font-black uppercase lg:hidden" type="button" onClick={() => setFilterOpen(true)}><SlidersHorizontal className="size-4" />Bộ lọc</button><span className="hidden text-xs font-bold text-neutral-500 lg:block">Lọc theo phong cách của bạn</span><select className="bg-transparent text-xs font-black uppercase outline-none" value={sort} onChange={(event) => setSort(event.target.value)} aria-label="Sắp xếp"><option value="newest">Mới nhất</option><option value="price-asc">Giá tăng dần</option><option value="price-desc">Giá giảm dần</option></select></div>{visibleProducts.length ? <div className="grid grid-cols-2 gap-x-3 gap-y-6 sm:grid-cols-3 xl:grid-cols-4">{visibleProducts.map((product) => <ProductCard product={product} key={product.id} />)}</div> : <div className="border border-dashed border-neutral-300 py-20 text-center"><h2 className="text-xl font-black">Chưa có sản phẩm phù hợp</h2><button className="mt-4 text-sm font-bold text-shopo-orange" type="button" onClick={() => { setCategory(""); setSize(""); }}>Xóa bộ lọc</button></div>}</section></div>{filterOpen ? <div className="fixed inset-0 z-50 bg-black/45 lg:hidden"><section className="absolute bottom-0 max-h-[85vh] w-full overflow-y-auto bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-black">Bộ lọc</h2><button onClick={() => setFilterOpen(false)} type="button" aria-label="Đóng bộ lọc"><X /></button></div><div className="mt-6">{filters}</div><button className="mt-8 w-full bg-ink py-3 text-sm font-black text-white" type="button" onClick={() => setFilterOpen(false)}>Xem {visibleProducts.length} sản phẩm</button></section></div> : null}</main>;
}
