import Link from "next/link";
import { ArrowUpRight, Mail, MapPin, Phone } from "lucide-react";

const columns = [
  { title: "Khám phá", links: [{ label: "Giày nữ", href: "/women/shoes" }, { label: "Giày nam", href: "/men/shoes" }, { label: "Giày trẻ em", href: "/kids/shoes" }, { label: "Dây lưng", href: "/men/belts" }] },
  { title: "Hỗ trợ", links: [{ label: "Hướng dẫn chọn size", href: "/#size-guide" }, { label: "Đổi trả & bảo hành", href: "/#service" }, { label: "Vận chuyển", href: "/#service" }, { label: "Liên hệ", href: "mailto:hello@shopo.vn" }] }
];

export function Footer() {
  return <footer className="bg-ink text-white"><div className="mx-auto grid max-w-[1440px] gap-10 px-4 py-14 sm:px-6 md:grid-cols-[1.4fr_1fr_1fr_1.3fr] lg:px-8"><div><Link className="text-3xl font-black tracking-[.16em]" href="/">SHOPO<span className="text-shopo-orange">.</span></Link><p className="mt-4 max-w-sm text-sm leading-6 text-white/65">Made for the everyday move. Giày dép và dây lưng cho nhịp sống của bạn.</p></div>{columns.map((column) => <nav key={column.title}><h2 className="text-xs font-black uppercase tracking-[.16em] text-shopo-orange">{column.title}</h2><div className="mt-4 grid gap-3">{column.links.map((link) => <Link className="text-sm text-white/70 hover:text-white" href={link.href} key={link.label}>{link.label}</Link>)}</div></nav>)}<div><h2 className="text-xs font-black uppercase tracking-[.16em] text-shopo-orange">Nhận drop mới</h2><p className="mt-4 text-sm leading-6 text-white/65">Nhận tin về sản phẩm mới, deal và cảm hứng phối đồ.</p><form className="mt-4 flex border border-white/25"><input className="min-w-0 flex-1 bg-transparent px-3 py-3 text-sm outline-none placeholder:text-white/40" placeholder="Email của bạn" aria-label="Email nhận tin" /><button className="grid w-12 place-items-center bg-shopo-orange" aria-label="Đăng ký"><ArrowUpRight className="size-5" /></button></form><div className="mt-5 grid gap-2 text-sm text-white/70"><a className="inline-flex items-center gap-2" href="tel:18001160"><Phone className="size-4 text-shopo-orange" />1800 1160</a><a className="inline-flex items-center gap-2" href="mailto:hello@shopo.vn"><Mail className="size-4 text-shopo-orange" />hello@shopo.vn</a><p className="inline-flex items-center gap-2"><MapPin className="size-4 text-shopo-orange" />Cửa hàng toàn quốc</p></div></div></div><div className="border-t border-white/10 px-4 py-4 text-center text-xs text-white/45">© 2026 SHOPO. Designed for every move.</div></footer>;
}
