import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, RefreshCw, Ruler, Truck } from "lucide-react";

const serviceItems = [{ label: "Giao nhanh toàn quốc", icon: Truck }, { label: "Đổi size trong 7 ngày", icon: RefreshCw }, { label: "Tư vấn size chuẩn", icon: Ruler }];

export function Hero() {
  return <section><div className="relative isolate min-h-[560px] overflow-hidden bg-ink sm:min-h-[650px]"><Image className="object-cover opacity-75" src="https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=2000&q=90" alt="SHOPO sneaker campaign" fill priority sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-r from-black via-black/60 to-transparent" /><div className="relative mx-auto flex min-h-[560px] max-w-[1440px] items-end px-4 pb-14 sm:min-h-[650px] sm:px-6 lg:px-8"><div className="max-w-2xl text-white"><p className="inline-flex bg-shopo-orange px-3 py-1.5 text-xs font-black uppercase tracking-[0.18em]">Drop 07 · Urban Shift</p><h1 className="mt-5 text-5xl font-black leading-[.9] tracking-[-.06em] sm:text-7xl lg:text-8xl">Bước ra.<br /><span className="text-shopo-orange">Bật chất.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-white/80">Giày dép và dây lưng được tạo ra cho nhịp sống không đứng yên. Chọn một đôi, đi theo cách của bạn.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="inline-flex items-center gap-2 bg-shopo-orange px-5 py-3.5 text-sm font-black uppercase tracking-[.12em] transition hover:bg-white hover:text-ink" href="/women/shoes">Khám phá giày <ArrowUpRight className="size-4" /></Link><Link className="inline-flex items-center border border-white/50 px-5 py-3.5 text-sm font-black uppercase tracking-[.12em] hover:bg-white hover:text-ink" href="/men/belts">Shop dây lưng</Link></div></div></div></div><div className="border-b border-neutral-200"><div className="mx-auto grid max-w-[1440px] divide-y divide-neutral-200 px-4 sm:grid-cols-3 sm:divide-x sm:divide-y-0 sm:px-6 lg:px-8">{serviceItems.map((item) => { const Icon = item.icon; return <div className="flex items-center justify-center gap-3 py-4 text-xs font-black uppercase tracking-[.1em]" key={item.label}><Icon className="size-4 text-shopo-orange" />{item.label}</div>; })}</div></div></section>;
}
