import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Footprints, Phone, Users } from "lucide-react";
import { contact } from "@/data/contact";

const highlights = [{ label: "Giày dép & dây lưng", icon: Footprints }, { label: "Nữ · Nam · Trẻ em", icon: Users }, { label: `Tư vấn ${contact.hotline}`, icon: Phone }];

export function Hero() {
  return <section><div className="relative isolate min-h-[440px] overflow-hidden bg-ink sm:min-h-[520px]"><Image className="object-cover opacity-75" src="https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=2000&q=90" alt="SHOPO sneaker campaign" fill priority sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-r from-black via-black/60 to-transparent" /><div className="relative mx-auto flex min-h-[440px] max-w-[1440px] items-end px-4 pb-10 sm:min-h-[520px] sm:pb-12 sm:px-6 lg:px-8"><div className="max-w-2xl text-white"><p className="inline-flex bg-shopo-orange px-3 py-1.5 text-xs font-black uppercase tracking-[0.18em]">Drop 07 · Urban Shift</p><h1 className="mt-5 text-5xl font-black leading-[.9] tracking-[-.06em] sm:text-6xl lg:text-7xl">Bước ra.<br /><span className="text-shopo-orange">Bật chất.</span></h1><p className="mt-5 max-w-lg text-base leading-7 text-white/90">Giày dép và dây lưng được tạo ra cho nhịp sống không đứng yên. Chọn một đôi, đi theo cách của bạn.</p><div className="mt-6 flex flex-wrap gap-3"><Link className="inline-flex min-h-12 items-center gap-2 rounded-control bg-shopo-orange px-5 py-3.5 text-sm font-black uppercase tracking-[.12em] transition hover:bg-white hover:text-ink focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white" href="/women/shoes">Khám phá bộ sưu tập <ArrowUpRight className="size-4" aria-hidden="true" /></Link><Link className="inline-flex min-h-12 items-center rounded-control border border-white/60 px-5 py-3.5 text-sm font-black uppercase tracking-[.12em] transition hover:bg-white hover:text-ink focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white" href="/men/belts">Xem dây lưng</Link></div></div></div></div><div className="border-b border-neutral-200"><div className="mx-auto grid max-w-[1440px] divide-y divide-neutral-200 px-4 sm:grid-cols-3 sm:divide-x sm:divide-y-0 sm:px-6 lg:px-8">{highlights.map((item) => { const Icon = item.icon; return <div className="flex items-center justify-center gap-3 py-4 text-xs font-black uppercase tracking-[.1em]" key={item.label}><Icon className="size-4 text-shopo-orange" aria-hidden="true" />{item.label}</div>; })}</div></div></section>;
}
